import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  coSnarkSidebar: [
    "overview",
    "primer/collabSNARKs-primer",
    "primer/mpc-primer",
    {
      type: "category",
      label: "Use Cases",
      items: [
        "use-cases/defi",
        "use-cases/ai",
        "use-cases/data-ownership",
        "use-cases/gaming",
      ],
    },
    {
      type: "category",
      label: "Getting Started",
      items: [
        "getting-started/quick-start",
        "getting-started/install",
        "getting-started/usage",
      ],
    },
    {
      type: "category",
      label: "co-circom CLI",
      link: { type: "doc", id: "co-circom-cli/co-circom" },
      items: [
        "co-circom-cli/split-input",
        "co-circom-cli/merge-input-shares",
        "co-circom-cli/split-witness",
        "co-circom-cli/generate-witness",
        "co-circom-cli/translate-witness",
        "co-circom-cli/generate-proof",
        "co-circom-cli/verify",
        "co-circom-cli/config",
      ],
    },
    {
      type: "category",
      label: "Examples",
      link: { type: "doc", id: "examples/examples" },
      items: ["examples/poseidon", "examples/kyc", "examples/multiplier2"],
    },
    {
      type: "category",
      label: "Design",
      items: ["design/mpc-vm", "design/known-issues", "design/roadmap"],
    },
    {
      type: "category",
      label: "Background Material",
      items: [
        "resources/circom",
        "resources/mpc",
        "resources/zkp",
        "resources/collsnarks",
      ],
    },
  ],
};

export default sidebars;
