import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  coSnarkSidebar: [
    "overview",
    "primer/mpc-primer",
    "primer/collabSNARKs-primer",
    {
      type: "category",
      label: "Getting Started",
      items: [
        "getting-started/quick-start-co-circom",
        "getting-started/quick-start-co-noir",
        "getting-started/install",
        "getting-started/usage",
      ],
    },
    {
      type: "category",
      label: "coCircom",
      link: { type: "doc", id: "co-circom/co-circom" },
      items: [
        {
          type: "category",
          label: "Command-Line Interface",
          link: { type: "doc", id: "co-circom/cli/cli" },
          items: [
            "co-circom/cli/split-input",
            "co-circom/cli/merge-input-shares",
            "co-circom/cli/split-witness",
            "co-circom/cli/generate-witness",
            "co-circom/cli/translate-witness",
            "co-circom/cli/generate-proof",
            "co-circom/cli/verify",
          ],
        },
        {
          type: "category",
          label: "Rust Library",
          link: { type: "doc", id: "co-circom/lib/lib" },
          items: [            
            "co-circom/lib/api",
            "co-circom/lib/example",
          ],
        }
      ],
    },
    {
      type: "category",
      label: "coNoir",
      link: { type: "doc", id: "co-noir/co-noir" },
      items: [
        {
          type: "category",
          label: "Command-Line Interface",
          link: { type: "doc", id: "co-noir/cli/cli" },
          items: [
            "co-noir/cli/split-input",
            "co-noir/cli/merge-input-shares",
            "co-noir/cli/split-witness",
            "co-noir/cli/generate-witness",
            "co-noir/cli/translate-witness",
            "co-noir/cli/build-proving-key",
            "co-noir/cli/split-proving-key",
            "co-noir/cli/translate-proving-key",
            "co-noir/cli/generate-proof",
            "co-noir/cli/build-and-generate-proof",
            "co-noir/cli/create-vk",
            "co-noir/cli/verify",
          ],
        },
        {
          type: "category",
          label: "Rust Library",
          link: { type: "doc", id: "co-noir/lib/lib" },
          items: [            
            "co-noir/lib/api",
            "co-noir/lib/example",
          ],
        },
      ],
    },
    "network-config",
    {
      type: "category",
      label: "Examples",
      link: { type: "doc", id: "examples/examples" },
      items: ["examples/poseidon", "examples/poseidon_noir", "examples/kyc", "examples/multiplier2"],
    },
    {
      type: "category",
      label: "Releases",
      items: ["releases/co-noir-nov"]
    },
    // {
    //   type: "category",
    //   label: "Design",
    //   items: ["design/mpc-vm", "design/known-issues", "design/roadmap"],
    // },
    {
      type: "category",
      label: "Background Material",
      items: [
        "resources/circom",
        "resources/mpc",
        "resources/zkp",
        "resources/collsnarks",
      ],
    },
    {
      type: "category",
      label: "Use Cases",
      items: [
        "use-cases/defi",
        "use-cases/ai",
        "use-cases/data-ownership",
        "use-cases/gaming",
      ],
    },
  ],
};

export default sidebars;
